apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramtun-client
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ramtun-client
  template:
    metadata:
      labels:
        app: ramtun-client
    spec:
      containers:
        - name: client
          image: ghcr.io/mrrevillod/ramtun-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
