events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    limit_req_zone $binary_remote_addr zone=general_limit:10m rate=10r/s;

    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        access_log off;

        location / {
            try_files $uri $uri/ /index.html;
        }

		location /api/ {
		    limit_req zone=general_limit burst=20 nodelay;
		    limit_req_status 429;

		    proxy_pass https://api-ramtun.inf.uct.cl/api/;

		    proxy_http_version 1.1;

		    # WebSocket / SSE
		    proxy_set_header Upgrade $http_upgrade;
		    proxy_set_header Connection $connection_upgrade;

		    # Forward headers
		    proxy_set_header Host api-ramtun.inf.uct.cl;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		    proxy_set_header X-Forwarded-Proto $scheme;
		    proxy_set_header X-Forwarded-Host $host;

		    # HTTPS
		    proxy_ssl_server_name on;

		    proxy_read_timeout 86400;
		    proxy_send_timeout 86400;
		}

        location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
