events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    map $http_origin $cors_origin {
        default "";
        "https://ramtun.inf.uct.cl" $http_origin;
        "http://localhost:5173" $http_origin;
    }

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
